# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.1-snapshot-3
	minecraft_version=26.1-snapshot-3
	# https://maven.parchmentmc.org/org/parchmentmc/data/
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=26.1-snapshot-3
    malilib_dependency=>=0.27.99-

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.1-snapshot-3

# Dependencies
	fabric_api_version=0.141.3+26.1

# (Jitpack.io) https://github.com/sakura-ryoko/malilib
#malilib_projectid = sakura-ryoko
#malilib_version = malilib:1.21.11-0.27.4
#mod_menu_version = 17.0.0-beta.2
