# Fabric Properties
    # check these on https://fallen-breath.github.io/fabric-versions/?&version=1.20.2
    minecraft_version=1.20.2
    # https://maven.parchmentmc.org/org/parchmentmc/data/
    parchment_version=2023.12.10

# Fabric Mod Metadata
    minecraft_dependency = 1.20.2
    malilib_dependency = >=0.17.0

# Build Information
    # The target mc versions for the mod during mod publishing, separated with \n
    game_versions = 1.20.2

# Dependencies
    fabric_api_version = 0.91.6+1.20.2

# https://masa.dy.fi/maven/fi/dy/masa/malilib/
# (Jitpack.io) https://github.com/sakura-ryoko/malilib
#malilib_projectid = sakura-ryoko
#malilib_version = malilib:1.20.2-65129
malilib_version = malilib-fabric-1.20.2:0.17.1-alpha.1
mod_menu_version = 8.0.1
